# config/packages/doctrine.yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            point: LongitudeOne\Spatial\DBAL\Types\Geography\PointType
            statut: App\Doctrine\DBAL\Types\StatutType
            role_enum: App\Doctrine\DBAL\Types\RoleEnumType
        mapping_types:
            point: point
            enum: string
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                AsBinary: App\Doctrine\AsBinaryFunction
                ST_Distance_Sphere: LongitudeOne\Spatial\ORM\Query\AST\Functions\MySql\DistanceSphere
                ST_GeomFromText: LongitudeOne\Spatial\ORM\Query\AST\Functions\MySql\GeomFromText
                ST_Within: LongitudeOne\Spatial\ORM\Query\AST\Functions\MySql\Within
                MBR_Contains: LongitudeOne\Spatial\ORM\Query\AST\Functions\MySql\MBRContains

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system