# knp_snappy:
#     pdf:
#         enabled:    true
#         binary:     '%env(WKHTMLTOPDF_PATH)%'
#         options:    []
#     image:
#         enabled:    true
#         binary:     '%env(WKHTMLTOIMAGE_PATH)%'
#         options:    []
# knp_snappy:
#     pdf:
#         enabled: true
#         binary: '%kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64' # Chemin vers wkhtmltopdf
#         options: []
#     image:
#         enabled: false
# config/packages/knp_snappy.yaml
knp_snappy:
    pdf:
        enabled: true
        binary: '%env(WKHTMLTOPDF_PATH)%'
        options:
            disable-local-file-access: true

