knp_paginator:
    page_range: 5                      # Nombre de pages affichées dans la pagination
    default_options:
        page_name: page                # Nom du paramètre de page dans l'URL
        sort_field_name: sort          # Nom du paramètre de tri
        sort_direction_name: direction # Nom du paramètre de direction de tri
        distinct: true                 # Assure des résultats distincts
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig' # Template Bootstrap 4