security:
    role_hierarchy:
        ROLE_ADMIN: ['ROLE_PROPRIETAIRE', 'ROLE_TRANSPORTEUR', 'ROLE_ETUDIANT']
        ROLE_PROPRIETAIRE: ['ROLE_ETUDIANT']
        ROLE_TRANSPORTEUR: ['ROLE_ETUDIANT']
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            user_checker: App\Security\BlockedUserChecker
            custom_authenticators:
                - App\Security\GoogleAuthenticator
            provider: app_user_provider
            form_login:
                login_path: app_utilisateur_signin
                check_path: app_login_check
                username_parameter: 'email'
                password_parameter: 'password'
                enable_csrf: true
                failure_path: app_utilisateur_signin
                failure_forward: false
                success_handler: App\Security\AuthenticationSuccessHandler
            logout:
                # path: app_logout
                target: app_utilisateur_signin

    access_control:
        - { path: ^/utilisateur/signin, roles: PUBLIC_ACCESS }
        - { path: ^/utilisateur/request-reset-code, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/verify-reset-code, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin/user/\d+/toggle-block, roles: ROLE_ADMIN, methods: POST }
        - { path: ^/utilisateur/request-reset-code, roles: PUBLIC_ACCESS }
        - { path: ^/verify-reset-code, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }

when@test:
    security:
        firewalls:
            main:
                # logout:
                #     path: app_logout
                #     target: app_utilisateur
                logout:
                    #path: app_logout
                    #target: app_utilisateur_signin 
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10