twig:
    form_themes: ['bootstrap_5_layout.html.twig']

twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        App\Twig\Components\: 'components/'
