vich_uploader:
    db_driver: orm
    mappings:
        voiture_photos:
            uri_prefix: /uploads/image
            upload_destination: '%kernel.project_dir%/public/uploads/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true