# config/packages/webauthn.yaml
webauthn:
    credential_repository: App\Repository\PublicKeyCredentialSourceRepository
    user_repository: App\Repository\UtilisateurRepository
    creation_profiles:
        default:
            rp:
                name: '%env(RELYING_PARTY_NAME)%'
                id: '%env(RELYING_PARTY_ID)%'
            authenticator_selection_criteria:
                user_verification: preferred
                require_resident_key: false
            attestation_conveyance: none
            timeout: 60000
    request_profiles:
        default:
            rp_id: '%env(RELYING_PARTY_ID)%'
            user_verification: preferred