controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login_check:
    path: /login_check
    methods: [POST]  # <-- This must be an array format
    # config/routes.yaml
app_logout:
    path: /logout