# config/routes.yaml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_admin_dashboard:
    path: /admin/dashboard
    controller: App\Controller\Admin\DashboardController::dashboard
    methods: GET

app_gestion_transport_dashboard:
    path: /adminTransport
    controller: App\Controller\Admin\GestionTransport\AdminTransportController::adminTransport
    

app_login_check:
    path: /login_check
    methods: [POST]

app_logout:
    path: /logout

connect_google_check:
    path: /connect/google/check
    controller: App\Controller\GoogleController::connectCheckAction

app_utilisateur_complete_registration:
    path: /utilisateur/complete_registration
    controller: App\Controller\RegistrationController::completeRegistration

student_guide:
    path: /student-guide
    controller: App\Controller\StudentGuideController::index
app_reservation_transport_show_ADMIN:
    path: /reservation/transport_ADMIN/{id}
    controller: App\Controller\GestionReservation\ReservationTransportController_ADMIN::show
    methods: [GET]
