# config/services.yaml
# imports:
#     - { resource: 'parameters.yaml' }

services:
    App\Security\GoogleAuthenticator:
        arguments:
            - '@knpu.oauth2.registry'
            - '@doctrine.orm.entity_manager'
            - '@router.default'

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Repository\GestionMeubles\CommandeRepository:
        arguments:
            $registry: '@doctrine'
            $entityManager: '@doctrine.orm.entity_manager'
            $mailer: '@mailer'

    App\Service\CartService:
        arguments:
            $panierRepository: '@App\Repository\GestionMeubles\PanierRepository'
            $lignePanierRepository: '@App\Repository\GestionMeubles\LignePanierRepository'
            $security: '@security.helper'

    App\Controller\GestionTransport\HomeController:
        public: true
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true

    App\WebSocket\ChatServer:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $utilisateurRepository: '@App\Repository\UtilisateurRepository'
        public: true # Add this line to make the service public