# config/services.yaml
# imports:
#     - { resource: 'parameters.yaml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # images_directory: '%kernel.project_dir%/assets/images'
    images_directory: '%kernel.project_dir%/public/Uploads/images'
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    voiture_photos_directory: '%photos_directory%'
    public_images_directory: '%kernel.project_dir%/public/assets/images'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    app_url: '%env(APP_URL)%'
    apiKey: '%env(OPENAI_API_KEY)%'
    uclassify_api_key: '%env(UCLASSIFY_API_KEY)%'
    uclassify_username: '%env(UCLASSIFY_USERNAME)%'
    google_nl_api_key: '%env(GOOGLE_NL_API_KEY)%'
    exchange_rate_api_key: '%env(EXCHANGE_RATE_API_KEY)%'

    app.sender_email: 'studar21@gmail.com'

    

services:
    App\Controller\Admin\DashboardController:
        arguments:
            $logger: '@logger'
    App\Security\GoogleAuthenticator:
        arguments:
            - '@knpu.oauth2.registry'
            - '@doctrine.orm.entity_manager'
            - '@router.default'
    App\Repository\GestionMeubles\CommandeRepository:
        arguments:
            $logger: '@monolog.logger'

  
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $mailerFrom: '%mailer_from%'
            $mailerFromName: '%mailer_from_name%'
            app.gemini_api_key: '%env(GEMINI_API_KEY)%'  # Add the Gemini API key parameter

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration explicite pour CommandeRepository
    # App\Repository\GestionMeubles\CommandeRepository:
    #     arguments:
    #         $registry: '@doctrine'                  # ManagerRegistry
    #         $entityManager: '@doctrine.orm.entity_manager'  # EntityManagerInterface
    #         $mailer: '@mailer'                      # MailerInterface

    # Configuration explicite pour CartService
    App\Service\CartService:
        arguments:
            $panierRepository: '@App\Repository\GestionMeubles\PanierRepository'
            $lignePanierRepository: '@App\Repository\GestionMeubles\LignePanierRepository'
            $security: '@security.helper'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Controller\GestionTransport\HomeController:
        public: true
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true

    App\Service\IAService:
        arguments:
            $client: '@http_client'
            $openaiApiKey: '%env(OPENAI_API_KEY)%'
    App\Service\PredictionService:
        arguments:
            $httpClient: '@http_client'
            $googleNlApiKey: '%google_nl_api_key%'
            $logger: '@monolog.logger'
    # Explicitly configure CurrencyConverterService
    App\Service\CurrencyConverterService:
        arguments:
            $exchangeRateApiKey: '%exchange_rate_api_key%'
